services:  
  webserver:       
    build:
      context: .
      dockerfile: Dockerfile
      args:
        copy_src_files: false  # Don't copy src in image, use volume mount instead
    restart: always      
    environment:
      SQLITE_DATABASE: /var/www/html/data/database/poznote.db
      POZNOTE_USERNAME: ${POZNOTE_USERNAME}
      POZNOTE_PASSWORD: ${POZNOTE_PASSWORD}
      HTTP_WEB_PORT: ${HTTP_WEB_PORT}
    ports:
      - "${HTTP_WEB_PORT}:80"
    volumes:
      - "./src:/var/www/html"
      - "./data:/var/www/html/data"
