#!/usr/bin/env python3
"""Regenerate src/public/css/devicon.css from the devicon language marks.

Usage:
    python3 tools/generate-devicon-icons.py > src/public/css/devicon.css

Issue #1444 asked for the recognisable mark of each programming language in the
code submenu of the slash menu, drawn in the menu's own icon colour rather than
in nineteen brand colours. Devicon ships those marks as brand-coloured artwork,
so each one is emitted as a CSS mask exactly like lucide.css does: the mask
keeps the shape and drops the colour, and the row paints it with `color`.

ICONS maps the class suffix to the devicon directory and file. Only single
variants that read as a silhouette are listed: a mark built from white cut-outs
on a coloured plate would mask into a solid block, so a variant is checked by
eye at 16px before it lands here. Languages devicon has no usable mark for
(SQL, XML) keep a Lucide icon in js/slash-command.js instead.

DEVICON_VERSION must stay in sync with the devicon entry in vendor.json, which
records what the committed CSS was generated from.
"""

import re
import sys
import urllib.parse
import urllib.request

DEVICON_VERSION = "v2.17.0"
URL = "https://raw.githubusercontent.com/devicons/devicon/{version}/icons/{folder}/{name}.svg"

# class suffix -> (devicon folder, svg file name)
ICONS = {
    "bash": ("bash", "bash-plain"),
    "cplusplus": ("cplusplus", "cplusplus-plain"),
    "csharp": ("csharp", "csharp-plain"),
    "css3": ("css3", "css3-plain"),
    "go": ("go", "go-plain"),
    "html5": ("html5", "html5-plain"),
    "java": ("java", "java-plain"),
    "javascript": ("javascript", "javascript-plain"),
    "json": ("json", "json-plain"),
    "markdown": ("markdown", "markdown-original"),
    "php": ("php", "php-plain"),
    "powershell": ("powershell", "powershell-plain"),
    "python": ("python", "python-plain"),
    "ruby": ("ruby", "ruby-plain"),
    "rust": ("rust", "rust-original"),
    "typescript": ("typescript", "typescript-plain"),
    "yaml": ("yaml", "yaml-plain"),
}

HEADER = """/* Devicon language marks - Generated CSS */
/* https://devicon.dev - generated by tools/generate-devicon-icons.py, never edited by hand */

/* One CSS mask per language, painted with `background-color: currentColor`
   exactly like lucide.css, so a row recolours its icon by setting `color`.
   The upstream SVGs are brand-coloured artwork; a mask keeps the shape and
   drops the colour, which is what issue #1444 asked for: the mark stays
   recognisable and the menu keeps one icon colour in every theme.

   The URL sits in --devicon-src so each icon states it once: mask-image still
   needs the -webkit- prefix for Safari, and the data URIs are long.

   `contain` rather than lucide's `100% 100%`: the slash menu hands its icons a
   box wider than it is tall, and a stretched language mark reads as the wrong
   logo. Centred and undistorted costs a pixel of width and nothing else. */
[class^="devicon-"], [class*=" devicon-"] {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  background-image: none;
  -webkit-mask-image: var(--devicon-src);
  mask-image: var(--devicon-src);
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: contain;
  mask-size: contain;
  -webkit-mask-position: center;
  mask-position: center;
}
"""

BLOCK = """
.devicon-{slug} {{
  --devicon-src: url("data:image/svg+xml,{data}");
}}
"""

# What a mask cannot survive. `fill="none"` and a stroke draw a shape the mask
# would fill solid once the colours go, and a gradient, a class or an inline
# opacity means the artwork relies on its paint. Refusing here is the point:
# a variant that changed upstream must be looked at, not silently flattened.
UNSAFE = [
    (r'fill\s*=\s*"\s*none\s*"', 'fill="none"'),
    (r'\bstroke\s*=', "a stroke"),
    (r'\bfill-opacity\s*=', "fill-opacity"),
    (r'\bopacity\s*=', "an opacity attribute"),
    (r'<style', "a <style> block"),
    (r'\bclass\s*=', "a class"),
    (r'<(?:linearGradient|radialGradient|mask|image)\b', "a gradient, mask or bitmap"),
]


PAINT_ATTRS = (
    r'\s(?:fill|style|color|stop-color|paint-order|overflow|isolation|mix-blend-mode'
    r'|inline-size|baseline-shift|letter-spacing|word-spacing|white-space'
    r'|(?:font|text|stroke|solid|shape)-[\w-]+)\s*=\s*"[^"]*"'
)


def clean_svg(name: str, svg: str) -> str:
    svg = re.sub(r"<\?xml.*?\?>", "", svg, flags=re.S)
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)

    for pattern, what in UNSAFE:
        if re.search(pattern, svg):
            raise SystemExit(f"{name}: {what} does not survive a mask, pick another variant")

    # The paint is what the mask throws away, and devicon's markdown mark also
    # carries a pile of inherited text properties. None of it is geometry.
    # fill-rule is NOT in here: it decides which parts of a path are holes.
    svg = re.sub(PAINT_ATTRS, "", svg)
    if "#" in svg:
        raise SystemExit(f"{name}: a colour is still in the markup, it would land in the stylesheet")

    svg = svg.replace('"', "'")
    return re.sub(r"\s+", " ", svg).strip()


def encode_svg(svg: str) -> str:
    return urllib.parse.quote(svg, safe="")


def fetch(folder: str, name: str) -> str:
    url = URL.format(version=DEVICON_VERSION, folder=folder, name=name)
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode("utf-8")


def main() -> int:
    out = [HEADER]
    for slug, (folder, name) in sorted(ICONS.items()):
        svg = clean_svg(name, fetch(folder, name))
        out.append(BLOCK.format(slug=slug, data=encode_svg(svg)))
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
