<?php
require 'auth.php';
requireAuth();

require_once 'config.php';
require_once 'db_connect.php';
require_once 'functions.php';

$workspace = isset($_GET['workspace']) ? trim($_GET['workspace']) : '';
$backUrl = 'index.php';
if ($workspace !== '') {
    $backUrl .= '?workspace=' . urlencode($workspace);
}

$currentLanguage = getUserLanguage();

$pageTranslations = [
    'en' => [
        'intro' => 'This page lists the Markdown and safe HTML syntax supported by Poznote preview, with an example for each item.',
        'filter_placeholder' => 'Filter syntax examples...',
        'no_results' => 'No syntax examples match your search.',
        'nav_label' => 'Markdown syntax sections',
        'nav' => [
            'text' => 'Text',
            'blocks' => 'Blocks',
            'lists' => 'Lists',
            'tables' => 'Tables',
            'advanced' => 'Advanced',
            'html' => 'Allowed HTML',
        ],
        'sections' => [
            'text' => 'Text and inline styles',
            'blocks' => 'Blocks',
            'lists' => 'Lists',
            'tables' => 'Tables',
            'advanced' => 'Advanced',
            'html' => 'Allowed HTML',
        ],
        'cards' => [
            'headings' => ['title' => 'Headings', 'description' => 'Heading levels 1 to 6 are supported.'],
            'emphasis' => ['title' => 'Bold, italic and strikethrough', 'description' => 'Bold, italic and strikethrough syntax is supported with asterisks or underscores.'],
            'highlight_color_code' => ['title' => 'Highlight, color and inline code', 'description' => 'Poznote supports highlight with ==...==, inline code, and preserves colored spans generated by the editor.'],
            'links_refs' => ['title' => 'Links and note references', 'description' => 'Markdown links, plain URLs, angle-bracket URLs, internal note links and [[Note title]] references are supported.'],
            'images_breaks' => ['title' => 'Images and line breaks', 'description' => 'Standard images and visible line breaks are rendered in preview.'],
            'code_blocks' => ['title' => 'Code blocks', 'description' => 'Fenced code blocks support syntax highlighting. The languages normal and code keep a plain rendering.'],
            'blockquotes' => ['title' => 'Blockquotes', 'description' => 'Blockquotes can span multiple consecutive lines.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote recognizes Note, Tip, Important, Warning and Caution callouts.'],
            'horizontal_rules' => ['title' => 'Horizontal rules', 'description' => 'Three or more dashes, asterisks or underscores create a separator.'],
            'bullet_lists' => ['title' => 'Bullet lists', 'description' => 'The markers -, * and + are accepted.'],
            'ordered_lists' => ['title' => 'Ordered lists', 'description' => 'Standard numbered lists and Poznote nested numbering are supported.'],
            'nested_lists' => ['title' => 'Nested lists', 'description' => 'Indentation creates nested list levels.'],
            'task_lists' => ['title' => 'Task lists', 'description' => 'Task lists use checkboxes in preview.'],
            'basic_tables' => ['title' => 'Basic tables', 'description' => 'A separator row is required for Poznote to detect a table.'],
            'table_alignment' => ['title' => 'Column alignment', 'description' => 'Use colons in the separator row to align columns left, center or right.'],
            'math' => ['title' => 'Math', 'description' => 'Inline and block math are rendered with KaTeX when available.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Mermaid diagrams are recognized inside mermaid fenced code blocks.'],
            'media' => ['title' => 'Media', 'description' => 'Safe video and audio tags with local or HTTP(S) sources are preserved.'],
            'details_summary' => ['title' => 'Details and summary', 'description' => 'The details and summary tags are allowed.'],
            'underline_linebreaks' => ['title' => 'Underline and line breaks', 'description' => 'The u and br tags are preserved.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Iframes are limited to trusted domains allowed by Poznote configuration.'],
        ],
    ],
    'fr' => [
        'intro' => 'Cette page récapitule la syntaxe Markdown et HTML sûre prise en charge par la prévisualisation Poznote, avec un exemple pour chaque élément.',
        'filter_placeholder' => 'Filtrer les exemples de syntaxe...',
        'no_results' => 'Aucun exemple de syntaxe ne correspond à votre recherche.',
        'nav_label' => 'Sections de syntaxe Markdown',
        'nav' => [
            'text' => 'Texte',
            'blocks' => 'Blocs',
            'lists' => 'Listes',
            'tables' => 'Tableaux',
            'advanced' => 'Avancé',
            'html' => 'HTML autorisé',
        ],
        'sections' => [
            'text' => 'Texte et styles inline',
            'blocks' => 'Blocs',
            'lists' => 'Listes',
            'tables' => 'Tableaux',
            'advanced' => 'Fonctionnalités avancées',
            'html' => 'HTML autorisé',
        ],
        'cards' => [
            'headings' => ['title' => 'Titres', 'description' => 'Les titres de niveau 1 à 6 sont supportés.'],
            'emphasis' => ['title' => 'Gras, italique et barré', 'description' => 'Le gras, l’italique et le barré fonctionnent avec des astérisques ou des underscores.'],
            'highlight_color_code' => ['title' => 'Surlignage, couleur et code inline', 'description' => 'Poznote prend en charge le surlignage avec ==...==, le code inline et conserve les spans colorés générés par l’éditeur.'],
            'links_refs' => ['title' => 'Liens et références de notes', 'description' => 'Les liens Markdown, les URLs simples, les URLs entre chevrons, les liens internes et les références [[Titre de note]] sont supportés.'],
            'images_breaks' => ['title' => 'Images et retours à la ligne', 'description' => 'Les images standard et les retours à la ligne visibles sont rendus en prévisualisation.'],
            'code_blocks' => ['title' => 'Blocs de code', 'description' => 'Les blocs de code clôturés prennent en charge la coloration syntaxique. Les langages normal et code gardent un rendu simple.'],
            'blockquotes' => ['title' => 'Citations', 'description' => 'Les citations peuvent s’étendre sur plusieurs lignes consécutives.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote reconnaît les callouts Note, Tip, Important, Warning et Caution.'],
            'horizontal_rules' => ['title' => 'Séparateurs', 'description' => 'Trois tirets, astérisques ou underscores ou plus créent un séparateur.'],
            'bullet_lists' => ['title' => 'Listes à puces', 'description' => 'Les marqueurs -, * et + sont acceptés.'],
            'ordered_lists' => ['title' => 'Listes numérotées', 'description' => 'Les listes numérotées classiques et la numérotation imbriquée de Poznote sont supportées.'],
            'nested_lists' => ['title' => 'Listes imbriquées', 'description' => 'L’indentation crée des niveaux de liste imbriqués.'],
            'task_lists' => ['title' => 'Checklists', 'description' => 'Les listes de tâches utilisent des cases à cocher en prévisualisation.'],
            'basic_tables' => ['title' => 'Tableaux simples', 'description' => 'Une ligne de séparation est obligatoire pour que Poznote reconnaisse un tableau.'],
            'table_alignment' => ['title' => 'Alignement des colonnes', 'description' => 'Utilisez les deux-points dans la ligne de séparation pour aligner les colonnes à gauche, au centre ou à droite.'],
            'math' => ['title' => 'Math', 'description' => 'Les formules inline et en bloc sont rendues avec KaTeX quand il est disponible.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Les diagrammes Mermaid sont reconnus dans les blocs de code clôturés mermaid.'],
            'media' => ['title' => 'Médias', 'description' => 'Les balises vidéo et audio sûres avec des sources locales ou HTTP(S) sont conservées.'],
            'details_summary' => ['title' => 'Details et summary', 'description' => 'Les balises details et summary sont autorisées.'],
            'underline_linebreaks' => ['title' => 'Soulignement et sauts de ligne', 'description' => 'Les balises u et br sont conservées.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Les iframes sont limitées aux domaines de confiance autorisés par la configuration Poznote.'],
        ],
    ],
    'de' => [
        'intro' => 'Diese Seite fasst die von der Poznote-Vorschau unterstützte Markdown- und sichere HTML-Syntax zusammen, jeweils mit einem Beispiel.',
        'filter_placeholder' => 'Syntaxbeispiele filtern...',
        'no_results' => 'Keine Syntaxbeispiele entsprechen Ihrer Suche.',
        'nav_label' => 'Markdown-Syntaxabschnitte',
        'nav' => [
            'text' => 'Text',
            'blocks' => 'Blöcke',
            'lists' => 'Listen',
            'tables' => 'Tabellen',
            'advanced' => 'Erweitert',
            'html' => 'Erlaubtes HTML',
        ],
        'sections' => [
            'text' => 'Text und Inline-Stile',
            'blocks' => 'Blöcke',
            'lists' => 'Listen',
            'tables' => 'Tabellen',
            'advanced' => 'Erweiterte Funktionen',
            'html' => 'Erlaubtes HTML',
        ],
        'cards' => [
            'headings' => ['title' => 'Überschriften', 'description' => 'Überschriften der Ebenen 1 bis 6 werden unterstützt.'],
            'emphasis' => ['title' => 'Fett, kursiv und durchgestrichen', 'description' => 'Fett, kursiv und durchgestrichen funktionieren mit Sternchen oder Unterstrichen.'],
            'highlight_color_code' => ['title' => 'Hervorhebung, Farbe und Inline-Code', 'description' => 'Poznote unterstützt Hervorhebung mit ==...==, Inline-Code und bewahrt farbige Spans aus dem Editor.'],
            'links_refs' => ['title' => 'Links und Notizverweise', 'description' => 'Markdown-Links, reine URLs, URLs in spitzen Klammern, interne Notizlinks und [[Notiztitel]]-Verweise werden unterstützt.'],
            'images_breaks' => ['title' => 'Bilder und Zeilenumbrüche', 'description' => 'Standardbilder und sichtbare Zeilenumbrüche werden in der Vorschau gerendert.'],
            'code_blocks' => ['title' => 'Codeblöcke', 'description' => 'Eingezäunte Codeblöcke unterstützen Syntaxhervorhebung. Die Sprachen normal und code bleiben schlicht.'],
            'blockquotes' => ['title' => 'Zitate', 'description' => 'Zitate können sich über mehrere aufeinanderfolgende Zeilen erstrecken.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote erkennt die Callouts Note, Tip, Important, Warning und Caution.'],
            'horizontal_rules' => ['title' => 'Trennlinien', 'description' => 'Drei oder mehr Bindestriche, Sternchen oder Unterstriche erzeugen einen Trenner.'],
            'bullet_lists' => ['title' => 'Aufzählungslisten', 'description' => 'Die Marker -, * und + werden akzeptiert.'],
            'ordered_lists' => ['title' => 'Nummerierte Listen', 'description' => 'Standardnummerierungen und Poznotes verschachtelte Nummerierung werden unterstützt.'],
            'nested_lists' => ['title' => 'Verschachtelte Listen', 'description' => 'Einrückung erzeugt verschachtelte Listenebenen.'],
            'task_lists' => ['title' => 'Aufgabenlisten', 'description' => 'Aufgabenlisten verwenden Kontrollkästchen in der Vorschau.'],
            'basic_tables' => ['title' => 'Einfache Tabellen', 'description' => 'Eine Trennzeile ist erforderlich, damit Poznote eine Tabelle erkennt.'],
            'table_alignment' => ['title' => 'Spaltenausrichtung', 'description' => 'Doppelpunkte in der Trennzeile richten Spalten links, mittig oder rechts aus.'],
            'math' => ['title' => 'Mathematik', 'description' => 'Inline- und Block-Mathematik wird mit KaTeX gerendert, wenn verfügbar.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Mermaid-Diagramme werden in mermaid-Codeblöcken erkannt.'],
            'media' => ['title' => 'Medien', 'description' => 'Sichere Video- und Audio-Tags mit lokalen oder HTTP(S)-Quellen bleiben erhalten.'],
            'details_summary' => ['title' => 'Details und Summary', 'description' => 'Die Tags details und summary sind erlaubt.'],
            'underline_linebreaks' => ['title' => 'Unterstreichung und Zeilenumbrüche', 'description' => 'Die Tags u und br bleiben erhalten.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Iframes sind auf vertrauenswürdige Domains beschränkt, die in der Poznote-Konfiguration erlaubt sind.'],
        ],
    ],
    'es' => [
        'intro' => 'Esta página resume la sintaxis Markdown y HTML segura compatible con la vista previa de Poznote, con un ejemplo para cada elemento.',
        'filter_placeholder' => 'Filtrar ejemplos de sintaxis...',
        'no_results' => 'Ningún ejemplo de sintaxis coincide con su búsqueda.',
        'nav_label' => 'Secciones de sintaxis Markdown',
        'nav' => [
            'text' => 'Texto',
            'blocks' => 'Bloques',
            'lists' => 'Listas',
            'tables' => 'Tablas',
            'advanced' => 'Avanzado',
            'html' => 'HTML permitido',
        ],
        'sections' => [
            'text' => 'Texto y estilos inline',
            'blocks' => 'Bloques',
            'lists' => 'Listas',
            'tables' => 'Tablas',
            'advanced' => 'Funciones avanzadas',
            'html' => 'HTML permitido',
        ],
        'cards' => [
            'headings' => ['title' => 'Encabezados', 'description' => 'Se admiten encabezados de nivel 1 a 6.'],
            'emphasis' => ['title' => 'Negrita, cursiva y tachado', 'description' => 'La sintaxis de negrita, cursiva y tachado funciona con asteriscos o guiones bajos.'],
            'highlight_color_code' => ['title' => 'Resaltado, color y código inline', 'description' => 'Poznote admite el resaltado con ==...==, el código inline y conserva los spans coloreados generados por el editor.'],
            'links_refs' => ['title' => 'Enlaces y referencias de notas', 'description' => 'Se admiten enlaces Markdown, URLs simples, URLs entre corchetes angulares, enlaces internos y referencias [[Título de nota]].'],
            'images_breaks' => ['title' => 'Imágenes y saltos de línea', 'description' => 'Las imágenes estándar y los saltos de línea visibles se renderizan en la vista previa.'],
            'code_blocks' => ['title' => 'Bloques de código', 'description' => 'Los bloques de código con cercas admiten resaltado de sintaxis. Los lenguajes normal y code mantienen un renderizado simple.'],
            'blockquotes' => ['title' => 'Citas', 'description' => 'Las citas pueden abarcar varias líneas consecutivas.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote reconoce los callouts Note, Tip, Important, Warning y Caution.'],
            'horizontal_rules' => ['title' => 'Separadores', 'description' => 'Tres o más guiones, asteriscos o guiones bajos crean un separador.'],
            'bullet_lists' => ['title' => 'Listas con viñetas', 'description' => 'Se aceptan los marcadores -, * y +.'],
            'ordered_lists' => ['title' => 'Listas numeradas', 'description' => 'Se admiten las listas numeradas estándar y la numeración anidada de Poznote.'],
            'nested_lists' => ['title' => 'Listas anidadas', 'description' => 'La indentación crea niveles de lista anidados.'],
            'task_lists' => ['title' => 'Listas de tareas', 'description' => 'Las listas de tareas usan casillas de verificación en la vista previa.'],
            'basic_tables' => ['title' => 'Tablas simples', 'description' => 'Se requiere una fila separadora para que Poznote detecte una tabla.'],
            'table_alignment' => ['title' => 'Alineación de columnas', 'description' => 'Usa dos puntos en la fila separadora para alinear columnas a la izquierda, al centro o a la derecha.'],
            'math' => ['title' => 'Matemáticas', 'description' => 'Las fórmulas inline y en bloque se renderizan con KaTeX cuando está disponible.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Los diagramas Mermaid se reconocen dentro de bloques de código mermaid.'],
            'media' => ['title' => 'Medios', 'description' => 'Se conservan las etiquetas seguras de vídeo y audio con fuentes locales o HTTP(S).'],
            'details_summary' => ['title' => 'Details y summary', 'description' => 'Las etiquetas details y summary están permitidas.'],
            'underline_linebreaks' => ['title' => 'Subrayado y saltos de línea', 'description' => 'Las etiquetas u y br se conservan.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Los iframes se limitan a dominios de confianza permitidos por la configuración de Poznote.'],
        ],
    ],
    'pt' => [
        'intro' => 'Esta página resume a sintaxe Markdown e HTML segura suportada pela visualização do Poznote, com um exemplo para cada item.',
        'filter_placeholder' => 'Filtrar exemplos de sintaxe...',
        'no_results' => 'Nenhum exemplo de sintaxe corresponde à sua pesquisa.',
        'nav_label' => 'Seções de sintaxe Markdown',
        'nav' => [
            'text' => 'Texto',
            'blocks' => 'Blocos',
            'lists' => 'Listas',
            'tables' => 'Tabelas',
            'advanced' => 'Avançado',
            'html' => 'HTML permitido',
        ],
        'sections' => [
            'text' => 'Texto e estilos inline',
            'blocks' => 'Blocos',
            'lists' => 'Listas',
            'tables' => 'Tabelas',
            'advanced' => 'Recursos avançados',
            'html' => 'HTML permitido',
        ],
        'cards' => [
            'headings' => ['title' => 'Títulos', 'description' => 'Títulos de nível 1 a 6 são suportados.'],
            'emphasis' => ['title' => 'Negrito, itálico e tachado', 'description' => 'A sintaxe de negrito, itálico e tachado funciona com asteriscos ou sublinhados.'],
            'highlight_color_code' => ['title' => 'Destaque, cor e código inline', 'description' => 'O Poznote suporta destaque com ==...==, código inline e preserva spans coloridos gerados pelo editor.'],
            'links_refs' => ['title' => 'Links e referências de notas', 'description' => 'Links Markdown, URLs simples, URLs entre sinais de menor e maior, links internos e referências [[Título da nota]] são suportados.'],
            'images_breaks' => ['title' => 'Imagens e quebras de linha', 'description' => 'Imagens padrão e quebras de linha visíveis são renderizadas na visualização.'],
            'code_blocks' => ['title' => 'Blocos de código', 'description' => 'Blocos de código cercados suportam realce de sintaxe. As linguagens normal e code mantêm uma renderização simples.'],
            'blockquotes' => ['title' => 'Citações', 'description' => 'As citações podem se estender por várias linhas consecutivas.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'O Poznote reconhece os callouts Note, Tip, Important, Warning e Caution.'],
            'horizontal_rules' => ['title' => 'Separadores', 'description' => 'Três ou mais hífens, asteriscos ou sublinhados criam um separador.'],
            'bullet_lists' => ['title' => 'Listas com marcadores', 'description' => 'Os marcadores -, * e + são aceitos.'],
            'ordered_lists' => ['title' => 'Listas numeradas', 'description' => 'Listas numeradas padrão e a numeração aninhada do Poznote são suportadas.'],
            'nested_lists' => ['title' => 'Listas aninhadas', 'description' => 'A indentação cria níveis de lista aninhados.'],
            'task_lists' => ['title' => 'Listas de tarefas', 'description' => 'Listas de tarefas usam caixas de seleção na visualização.'],
            'basic_tables' => ['title' => 'Tabelas simples', 'description' => 'Uma linha separadora é obrigatória para que o Poznote detecte uma tabela.'],
            'table_alignment' => ['title' => 'Alinhamento de colunas', 'description' => 'Use dois-pontos na linha separadora para alinhar colunas à esquerda, ao centro ou à direita.'],
            'math' => ['title' => 'Matemática', 'description' => 'Fórmulas inline e em bloco são renderizadas com KaTeX quando disponível.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Diagramas Mermaid são reconhecidos dentro de blocos de código mermaid.'],
            'media' => ['title' => 'Mídia', 'description' => 'Tags seguras de vídeo e áudio com fontes locais ou HTTP(S) são preservadas.'],
            'details_summary' => ['title' => 'Details e summary', 'description' => 'As tags details e summary são permitidas.'],
            'underline_linebreaks' => ['title' => 'Sublinhado e quebras de linha', 'description' => 'As tags u e br são preservadas.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Iframes são limitados a domínios confiáveis permitidos pela configuração do Poznote.'],
        ],
    ],
    'ru' => [
        'intro' => 'На этой странице собраны синтаксис Markdown и безопасный HTML, поддерживаемые предпросмотром Poznote, с примером для каждого элемента.',
        'filter_placeholder' => 'Фильтровать примеры синтаксиса...',
        'no_results' => 'Нет примеров синтаксиса, соответствующих вашему запросу.',
        'nav_label' => 'Разделы синтаксиса Markdown',
        'nav' => [
            'text' => 'Текст',
            'blocks' => 'Блоки',
            'lists' => 'Списки',
            'tables' => 'Таблицы',
            'advanced' => 'Дополнительно',
            'html' => 'Разрешённый HTML',
        ],
        'sections' => [
            'text' => 'Текст и встроенные стили',
            'blocks' => 'Блоки',
            'lists' => 'Списки',
            'tables' => 'Таблицы',
            'advanced' => 'Расширенные возможности',
            'html' => 'Разрешённый HTML',
        ],
        'cards' => [
            'headings' => ['title' => 'Заголовки', 'description' => 'Поддерживаются заголовки уровней с 1 по 6.'],
            'emphasis' => ['title' => 'Жирный, курсив и зачёркивание', 'description' => 'Жирный, курсив и зачёркивание работают со звёздочками и подчёркиваниями.'],
            'highlight_color_code' => ['title' => 'Выделение, цвет и встроенный код', 'description' => 'Poznote поддерживает выделение через ==...==, встроенный код и сохраняет цветные span, созданные редактором.'],
            'links_refs' => ['title' => 'Ссылки и ссылки на заметки', 'description' => 'Поддерживаются Markdown-ссылки, обычные URL, URL в угловых скобках, внутренние ссылки на заметки и ссылки вида [[Название заметки]].'],
            'images_breaks' => ['title' => 'Изображения и переносы строк', 'description' => 'Стандартные изображения и видимые переносы строк отображаются в предпросмотре.'],
            'code_blocks' => ['title' => 'Блоки кода', 'description' => 'Ограждённые блоки кода поддерживают подсветку синтаксиса. Языки normal и code остаются без дополнительного оформления.'],
            'blockquotes' => ['title' => 'Цитаты', 'description' => 'Цитаты могут занимать несколько подряд идущих строк.'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote распознаёт callouts Note, Tip, Important, Warning и Caution.'],
            'horizontal_rules' => ['title' => 'Разделители', 'description' => 'Три и более дефиса, звёздочки или подчёркивания создают разделитель.'],
            'bullet_lists' => ['title' => 'Маркированные списки', 'description' => 'Допустимы маркеры -, * и +.'],
            'ordered_lists' => ['title' => 'Нумерованные списки', 'description' => 'Поддерживаются стандартные нумерованные списки и вложенная нумерация Poznote.'],
            'nested_lists' => ['title' => 'Вложенные списки', 'description' => 'Отступы создают вложенные уровни списка.'],
            'task_lists' => ['title' => 'Списки задач', 'description' => 'Списки задач используют флажки в предпросмотре.'],
            'basic_tables' => ['title' => 'Простые таблицы', 'description' => 'Для распознавания таблицы Poznote требуется строка-разделитель.'],
            'table_alignment' => ['title' => 'Выравнивание столбцов', 'description' => 'Используйте двоеточия в строке-разделителе, чтобы выровнять столбцы по левому краю, по центру или по правому краю.'],
            'math' => ['title' => 'Математика', 'description' => 'Встроенные и блочные формулы отображаются через KaTeX, если он доступен.'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Диаграммы Mermaid распознаются внутри блоков кода mermaid.'],
            'media' => ['title' => 'Медиа', 'description' => 'Безопасные теги video и audio с локальными или HTTP(S)-источниками сохраняются.'],
            'details_summary' => ['title' => 'Details и summary', 'description' => 'Теги details и summary разрешены.'],
            'underline_linebreaks' => ['title' => 'Подчёркивание и переносы строк', 'description' => 'Теги u и br сохраняются.'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Iframes ограничены доверенными доменами, разрешёнными конфигурацией Poznote.'],
        ],
    ],
    'zh-cn' => [
        'intro' => '此页面汇总了 Poznote 预览支持的 Markdown 和安全 HTML 语法，并为每一项提供示例。',
        'filter_placeholder' => '筛选语法示例...',
        'no_results' => '没有与您的搜索匹配的语法示例。',
        'nav_label' => 'Markdown 语法分区',
        'nav' => [
            'text' => '文本',
            'blocks' => '块级内容',
            'lists' => '列表',
            'tables' => '表格',
            'advanced' => '高级',
            'html' => '允许的 HTML',
        ],
        'sections' => [
            'text' => '文本和行内样式',
            'blocks' => '块级内容',
            'lists' => '列表',
            'tables' => '表格',
            'advanced' => '高级功能',
            'html' => '允许的 HTML',
        ],
        'cards' => [
            'headings' => ['title' => '标题', 'description' => '支持 1 到 6 级标题。'],
            'emphasis' => ['title' => '加粗、斜体和删除线', 'description' => '加粗、斜体和删除线语法都支持使用星号或下划线。'],
            'highlight_color_code' => ['title' => '高亮、颜色和行内代码', 'description' => 'Poznote 支持通过 ==...== 高亮、行内代码，并保留编辑器生成的彩色 span。'],
            'links_refs' => ['title' => '链接和笔记引用', 'description' => '支持 Markdown 链接、普通 URL、尖括号 URL、内部笔记链接以及 [[笔记标题]] 引用。'],
            'images_breaks' => ['title' => '图片和换行', 'description' => '标准图片和可见换行会在预览中渲染。'],
            'code_blocks' => ['title' => '代码块', 'description' => '围栏代码块支持语法高亮。normal 和 code 语言会保持朴素渲染。'],
            'blockquotes' => ['title' => '引用块', 'description' => '引用块可以跨越多行连续内容。'],
            'callouts' => ['title' => 'Callouts', 'description' => 'Poznote 可识别 Note、Tip、Important、Warning 和 Caution callout。'],
            'horizontal_rules' => ['title' => '分隔线', 'description' => '三个或更多的短横线、星号或下划线会生成分隔线。'],
            'bullet_lists' => ['title' => '无序列表', 'description' => '支持 -, * 和 + 作为列表标记。'],
            'ordered_lists' => ['title' => '有序列表', 'description' => '支持标准编号列表以及 Poznote 的嵌套编号。'],
            'nested_lists' => ['title' => '嵌套列表', 'description' => '缩进可以创建嵌套列表层级。'],
            'task_lists' => ['title' => '任务列表', 'description' => '任务列表在预览中使用复选框。'],
            'basic_tables' => ['title' => '基本表格', 'description' => 'Poznote 识别表格时必须包含分隔行。'],
            'table_alignment' => ['title' => '列对齐', 'description' => '在分隔行中使用冒号即可让列左对齐、居中或右对齐。'],
            'math' => ['title' => '数学公式', 'description' => '如果可用，行内和块级公式会通过 KaTeX 渲染。'],
            'mermaid' => ['title' => 'Mermaid', 'description' => 'Mermaid 图表会在 mermaid 围栏代码块中被识别。'],
            'media' => ['title' => '媒体', 'description' => '带本地或 HTTP(S) 来源的安全 video 和 audio 标签会被保留。'],
            'details_summary' => ['title' => 'Details 和 summary', 'description' => '允许使用 details 和 summary 标签。'],
            'underline_linebreaks' => ['title' => '下划线和换行', 'description' => 'u 和 br 标签会被保留。'],
            'iframes' => ['title' => 'Iframes', 'description' => 'Iframe 仅允许使用 Poznote 配置中信任的域名。'],
        ],
    ],
];

if (!isset($pageTranslations[$currentLanguage])) {
    $baseLanguage = explode('-', $currentLanguage, 2)[0];
    $currentLanguage = isset($pageTranslations[$baseLanguage]) ? $baseLanguage : 'en';
}

$copy = $pageTranslations[$currentLanguage];

$filterPlaceholder = isset($copy['filter_placeholder']) ? $copy['filter_placeholder'] : 'Filter syntax examples...';
$noResultsText = isset($copy['no_results']) ? $copy['no_results'] : 'No syntax examples match your search.';

$sections = [
    'text' => ['headings', 'emphasis', 'highlight_color_code', 'links_refs', 'images_breaks'],
    'blocks' => ['code_blocks', 'blockquotes', 'callouts', 'horizontal_rules'],
    'lists' => ['bullet_lists', 'ordered_lists', 'nested_lists', 'task_lists'],
    'tables' => ['basic_tables', 'table_alignment'],
    'advanced' => ['math', 'mermaid', 'media'],
    'html' => ['details_summary', 'underline_linebreaks', 'iframes'],
];

$cardsInOrder = [];
foreach ($sections as $sectionId => $cardIds) {
    foreach ($cardIds as $cardId) {
        $cardsInOrder[] = [
            'section_id' => $sectionId,
            'card_id' => $cardId,
        ];
    }
}

$examples = [
    'headings' => "# Heading 1\n## Heading 2\n### Heading 3\n###### Heading 6",
    'emphasis' => "**Bold**\n__Bold__\n*Italic*\n_Italic_\n~~Strikethrough~~",
    'highlight_color_code' => "==Highlight==\n<span style=\"color: red;\">Colored text</span>\n`inline code`",
    'links_refs' => "[Website](https://example.com)\nhttps://example.com\n<https://example.com>\n[Internal note](index.php?note=123)\n[[Note title]]",
    'images_breaks' => "![Alt text](attachments/image.png)\nFirst line\nSecond line",
    'code_blocks' => "```javascript\nconsole.log('Poznote');\n```\n\n```normal\nPlain preformatted text.\n```",
    'blockquotes' => "> A blockquote\n> on multiple lines",
    'callouts' => "> **Note** Helpful information\n\n> **Tip** Quick tip\n\n> **Important** Key point\n\n> **Warning** Be careful\n\n> **Caution** Risk or precaution",
    'horizontal_rules' => "---\n***\n___",
    'bullet_lists' => "- Item\n* Item\n+ Item",
    'ordered_lists' => "1. First\n2. Second\n\n1. Parent\n1.1. Child\n1.2. Child",
    'nested_lists' => "- Parent\n  - Child\n    - Grandchild",
    'task_lists' => "- [ ] To do\n- [x] Done",
    'basic_tables' => "| Year | Amount | Notes |\n| --- | --- | --- |\n| 2023 | 120 | Draft |\n| 2024 | 180 | Done |",
    'table_alignment' => "| Left | Center | Right |\n| :--- | :---: | ---: |\n| A | B | C |\n| Text | Text | 123 |",
    'math' => "Inline: $E = mc^2$\n\n$$\n\\int_0^1 x^2 dx = \\frac{1}{3}\n$$",
    'mermaid' => "```mermaid\nflowchart TD\n    A[Idea] --> B[Note]\n    B --> C[Share]\n```",
    'media' => "<video src=\"attachments/demo.mp4\" controls></video>\n\n<audio src=\"attachments/audio.mp3\" controls></audio>",
    'details_summary' => "<details>\n<summary>Show more</summary>\nHidden content.\n</details>",
    'underline_linebreaks' => "<u>Underlined text</u>\nLine 1<br>Line 2",
    'iframes' => "<iframe src=\"https://www.youtube.com/embed/...\" loading=\"lazy\"></iframe>",
];
?>
<!DOCTYPE html>
<html lang="<?php echo htmlspecialchars($currentLanguage, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo t_h('markdown_syntax.page_title', [], 'Markdown syntax'); ?> - Poznote</title>
    <meta name="color-scheme" content="dark light">
    <script src="js/theme-init.js"></script>
    <link rel="stylesheet" href="css/lucide.css">
    <link rel="stylesheet" href="css/info.css">
    <link rel="stylesheet" href="css/markdown-syntax.css">
    <link rel="stylesheet" href="css/dark-mode/variables.css">
    <link rel="stylesheet" href="css/dark-mode/pages.css">
    <script src="js/theme-manager.js"></script>
</head>
<body>
    <div class="info-page markdown-syntax-page">
        <div class="info-buttons-back-container">
            <a class="btn btn-secondary" href="<?php echo htmlspecialchars($backUrl, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>" title="<?php echo t_h('common.back_to_notes', [], 'Notes'); ?>">
                <?php echo t_h('common.back_to_notes', [], 'Notes'); ?>
            </a>
        </div>

        <div class="info-content markdown-syntax-content">
            <p class="markdown-syntax-intro"><?php echo htmlspecialchars($copy['intro'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p>

            <div class="markdown-syntax-filter-bar">
                <div class="filter-input-wrapper">
                    <i class="lucide lucide-search markdown-syntax-filter-icon" aria-hidden="true"></i>
                    <input
                        type="text"
                        id="markdownSyntaxFilterInput"
                        class="filter-input"
                        placeholder="<?php echo htmlspecialchars($filterPlaceholder, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>"
                        aria-label="<?php echo htmlspecialchars($filterPlaceholder, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>"
                        autocomplete="off"
                    />
                    <button
                        type="button"
                        id="markdownSyntaxClearFilter"
                        class="clear-filter-btn initially-hidden"
                        title="<?php echo t_h('search.clear', [], 'Clear search'); ?>"
                        aria-label="<?php echo t_h('search.clear', [], 'Clear search'); ?>"
                    >
                        <i class="lucide lucide-x" aria-hidden="true"></i>
                    </button>
                </div>
                <div id="markdownSyntaxFilterStats" class="filter-stats initially-hidden"></div>
            </div>

            <div class="markdown-syntax-list" id="markdownSyntaxList">
                <?php foreach ($cardsInOrder as $item): ?>
                    <?php $sectionId = $item['section_id']; ?>
                    <?php $cardId = $item['card_id']; ?>
                    <article class="syntax-card" data-syntax-card>
                        <p class="syntax-card-category"><?php echo htmlspecialchars($copy['nav'][$sectionId], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p>
                        <h2><?php echo htmlspecialchars($copy['cards'][$cardId]['title'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></h2>
                        <p><?php echo htmlspecialchars($copy['cards'][$cardId]['description'], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p>
                        <pre><code><?php echo htmlspecialchars($examples[$cardId], ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></code></pre>
                    </article>
                <?php endforeach; ?>
            </div>

            <p id="markdownSyntaxNoResults" class="markdown-syntax-empty initially-hidden"><?php echo htmlspecialchars($noResultsText, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p>
        </div>
    </div>

    <script>
    (function () {
        var filterInput = document.getElementById('markdownSyntaxFilterInput');
        if (!filterInput) {
            return;
        }

        var clearButton = document.getElementById('markdownSyntaxClearFilter');
        var filterStats = document.getElementById('markdownSyntaxFilterStats');
        var noResults = document.getElementById('markdownSyntaxNoResults');
        var cards = Array.prototype.slice.call(document.querySelectorAll('[data-syntax-card]'));
        var totalCount = cards.length;

        cards.forEach(function (card) {
            card.dataset.filterText = card.textContent.toLowerCase();
        });

        function applyFilter() {
            var filterText = filterInput.value.trim().toLowerCase();
            var visibleCount = 0;

            cards.forEach(function (card) {
                var matches = !filterText || card.dataset.filterText.indexOf(filterText) !== -1;
                card.hidden = !matches;
                if (matches) {
                    visibleCount += 1;
                }
            });

            if (clearButton) {
                clearButton.classList.toggle('initially-hidden', filterText === '');
            }

            if (filterStats) {
                if (filterText) {
                    filterStats.textContent = visibleCount + ' / ' + totalCount;
                    filterStats.classList.remove('initially-hidden');
                } else {
                    filterStats.textContent = '';
                    filterStats.classList.add('initially-hidden');
                }
            }

            if (noResults) {
                noResults.classList.toggle('initially-hidden', visibleCount !== 0);
            }
        }

        filterInput.addEventListener('input', applyFilter);
        filterInput.addEventListener('keydown', function (event) {
            if (event.key === 'Escape' && filterInput.value !== '') {
                filterInput.value = '';
                applyFilter();
                filterInput.focus();
            }
        });

        if (clearButton) {
            clearButton.addEventListener('click', function () {
                filterInput.value = '';
                applyFilter();
                filterInput.focus();
            });
        }

        applyFilter();
    })();
    </script>
</body>
</html>