openapi: 3.0.3
info:
  title: Poznote API
  description: |
    REST API for Poznote - Note-taking application with workspaces, folders, tags and attachments support.
    
    ## Authentication
    All API requests require authentication. The API supports multiple methods:
    - **API Key**: Use the `X-API-Key` header with your API key
    - **Basic Auth**: Username and password via HTTP Basic Auth
    - **Session**: PHP session cookie
    
  version: 1.0.0
  contact:
    name: Poznote
    url: https://github.com/timothepoznanski/poznote

servers:
  - url: /src
    description: Local server

tags:
  - name: Notes
    description: Note management
  - name: Folders
    description: Folder management
  - name: Workspaces
    description: Workspace management
  - name: Tags
    description: Tag management
  - name: Attachments
    description: Attachment management
  - name: Favorites
    description: Favorites management

security:
  - ApiKeyAuth: []
  - BasicAuth: []
  - SessionAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BasicAuth:
      type: http
      scheme: basic
    SessionAuth:
      type: apiKey
      in: cookie
      name: PHPSESSID

  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        heading:
          type: string
        subheading:
          type: string
        entrycontent:
          type: string
        tags:
          type: string
        folder:
          type: string
        workspace:
          type: string
        favorite:
          type: integer
          enum: [0, 1]
        trash:
          type: integer
          enum: [0, 1]
        type:
          type: string
          enum: [note, task]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

paths:
  /api_list_notes.php:
    get:
      tags:
        - Notes
      summary: List notes
      parameters:
        - name: workspace
          in: query
          schema:
            type: string
        - name: folder
          in: query
          schema:
            type: string
        - name: search
          in: query
          schema:
            type: string
        - name: tag
          in: query
          schema:
            type: string
        - name: favorite
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Success

  /api_create_note.php:
    post:
      tags:
        - Notes
      summary: Create note
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - heading
              properties:
                heading:
                  type: string
                entrycontent:
                  type: string
                tags:
                  type: string
                folder_name:
                  type: string
                workspace:
                  type: string
      responses:
        '200':
          description: Note created

  /api_update_note.php:
    post:
      tags:
        - Notes
      summary: Update note
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer
                heading:
                  type: string
                entrycontent:
                  type: string
                tags:
                  type: string
      responses:
        '200':
          description: Note updated

  /api_delete_note.php:
    post:
      tags:
        - Notes
      summary: Delete note
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Note deleted

  /api_share_note.php:
    post:
      tags:
        - Notes
      summary: Share note
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                shared:
                  type: integer
                  enum: [0, 1]
      responses:
        '200':
          description: Sharing updated

  /api_workspaces.php:
    get:
      tags:
        - Workspaces
      summary: List workspaces
      responses:
        '200':
          description: Success
    post:
      tags:
        - Workspaces
      summary: Create workspace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Workspace created

  /api_list_tags.php:
    get:
      tags:
        - Tags
      summary: List tags
      parameters:
        - name: workspace
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success

  /api_favorites.php:
    post:
      tags:
        - Favorites
      summary: Toggle favorite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                favorite:
                  type: integer
                  enum: [0, 1]
      responses:
        '200':
          description: Success

  /api_attachments.php:
    get:
      tags:
        - Attachments
      summary: List attachments
      parameters:
        - name: note_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Success
    post:
      tags:
        - Attachments
      summary: Upload attachment
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                note_id:
                  type: integer
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Success

  /api_create_folder.php:
    post:
      tags:
        - Folders
      summary: Create folder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                folder_name:
                  type: string
                workspace:
                  type: string
      responses:
        '200':
          description: Folder created

  /api_delete_folder.php:
    post:
      tags:
        - Folders
      summary: Delete folder
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                folder_name:
                  type: string
                workspace:
                  type: string
      responses:
        '200':
          description: Folder deleted
