name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
        port: ${{ secrets.PROD_PORT || 22 }}
        script: |
          set -e
          echo "🚀 Starting production deployment.."
          
          cd ${{ secrets.PROD_PROJECT_PATH || '/root/poznote/poznote' }}
          
          # Check if .env file exists, if not create it from template
          if [ ! -f ".env" ]; then
            echo "⚠️  .env file not found, creating from template..."
            if [ -f ".env.template" ]; then
              cp .env.template .env
              echo "✅ .env file created from template"
            else
              echo "❌ Error: .env.template not found! Please run setup script first."
              exit 1
            fi
          else
            echo "✅ .env file found"
          fi
          
          # Pull the latest code
          echo "📥 Pulling latest code from repository..."
          git pull origin main
          
          # Build and deploy
          echo "🔄 Building and updating production services..."
          docker compose -f docker-compose.yml -f docker-compose-reverse-proxy.yml up -d --build --force-recreate
          
          echo "🧹 Cleaning up old images..."
          docker image prune -f
          
          echo "✅ Production deployment completed!"
          echo "📊 Deployed version: ${{ github.sha }}"
